name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Create .env file for testing
        run: |
          touch .env
          echo DATABASE_URL=postgres://postgres:postgres@localhost:5433/bcr_management_dashboard >> .env
      - name: Run database image for testing
        run: docker-compose up database
      - name: Migrate and seed database
        run: npm run migrate && npm run seed
      - name: Create .env file for deployment
        run: |
          rm .env
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}